"""empty message

Revision ID: 147dd9d10b18
Revises: a5cffa318ac2
Create Date: 2025-10-09 08:18:28.127798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147dd9d10b18'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('skin_color', sa.String(length=10), nullable=False),
    sa.Column('hair_color', sa.String(length=10), nullable=False),
    sa.Column('eye_color', sa.String(length=10), nullable=False),
    sa.Column('height', sa.String(length=3), nullable=False),
    sa.Column('mass', sa.String(length=3), nullable=False),
    sa.Column('birth_year', sa.String(length=6), nullable=False),
    sa.Column('homeworld', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
