"""empty message

Revision ID: 9025d8072c38
Revises: 147dd9d10b18
Create Date: 2025-10-16 18:56:41.775673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9025d8072c38'
down_revision = '147dd9d10b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('climate', sa.String(length=50), nullable=False),
    sa.Column('diameter', sa.String(length=6), nullable=False),
    sa.Column('rotation_period', sa.String(length=6), nullable=False),
    sa.Column('terrain', sa.String(length=120), nullable=False),
    sa.Column('gravity', sa.String(length=20), nullable=False),
    sa.Column('orbital_period', sa.String(length=6), nullable=False),
    sa.Column('population', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', name='unique_user_favorite')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_table('planet')
    # ### end Alembic commands ###
